import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Gundam(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/assets/gundam_unicorn.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[-80.03, -53.5, -4.92]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_0.geometry}
            material={materials.blinn20SG}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_12.geometry}
            material={nodes.Mesh_12.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_13.geometry}
            material={nodes.Mesh_13.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_25.geometry}
            material={nodes.Mesh_25.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_26.geometry}
            material={nodes.Mesh_26.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_27.geometry}
            material={nodes.Mesh_27.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_38.geometry}
            material={materials.blinn18SG}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_47.geometry}
            material={nodes.Mesh_47.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_48.geometry}
            material={nodes.Mesh_48.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_56.geometry}
            material={nodes.Mesh_56.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_57.geometry}
            material={nodes.Mesh_57.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_67.geometry}
            material={nodes.Mesh_67.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_68.geometry}
            material={nodes.Mesh_68.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_73.geometry}
            material={nodes.Mesh_73.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_74.geometry}
            material={nodes.Mesh_74.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_85.geometry}
            material={nodes.Mesh_85.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_86.geometry}
            material={nodes.Mesh_86.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_87.geometry}
            material={nodes.Mesh_87.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_1.geometry}
            material={nodes.Mesh_1.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_2.geometry}
            material={nodes.Mesh_2.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_3.geometry}
            material={nodes.Mesh_3.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_4.geometry}
            material={nodes.Mesh_4.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_5.geometry}
            material={nodes.Mesh_5.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_10.geometry}
            material={nodes.Mesh_10.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_11.geometry}
            material={nodes.Mesh_11.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_6.geometry}
            material={nodes.Mesh_6.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_7.geometry}
            material={nodes.Mesh_7.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_8.geometry}
            material={nodes.Mesh_8.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_9.geometry}
            material={nodes.Mesh_9.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_14.geometry}
            material={nodes.Mesh_14.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_15.geometry}
            material={nodes.Mesh_15.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_16.geometry}
            material={nodes.Mesh_16.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_17.geometry}
            material={nodes.Mesh_17.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_18.geometry}
            material={nodes.Mesh_18.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_19.geometry}
            material={nodes.Mesh_19.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_20.geometry}
            material={nodes.Mesh_20.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_21.geometry}
            material={nodes.Mesh_21.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_22.geometry}
            material={nodes.Mesh_22.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_23.geometry}
            material={nodes.Mesh_23.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_24.geometry}
            material={nodes.Mesh_24.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_28.geometry}
            material={nodes.Mesh_28.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_29.geometry}
            material={nodes.Mesh_29.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_30.geometry}
            material={nodes.Mesh_30.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_31.geometry}
            material={nodes.Mesh_31.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_32.geometry}
            material={nodes.Mesh_32.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_33.geometry}
            material={nodes.Mesh_33.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_34.geometry}
            material={nodes.Mesh_34.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_35.geometry}
            material={nodes.Mesh_35.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_36.geometry}
            material={nodes.Mesh_36.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_37.geometry}
            material={nodes.Mesh_37.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_39.geometry}
            material={nodes.Mesh_39.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_40.geometry}
            material={nodes.Mesh_40.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_41.geometry}
            material={nodes.Mesh_41.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_42.geometry}
            material={nodes.Mesh_42.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_43.geometry}
            material={nodes.Mesh_43.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_44.geometry}
            material={nodes.Mesh_44.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_45.geometry}
            material={nodes.Mesh_45.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_46.geometry}
            material={nodes.Mesh_46.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_49.geometry}
            material={materials.blinn4SG}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_50.geometry}
            material={nodes.Mesh_50.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_51.geometry}
            material={nodes.Mesh_51.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_52.geometry}
            material={nodes.Mesh_52.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_53.geometry}
            material={nodes.Mesh_53.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_54.geometry}
            material={nodes.Mesh_54.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_55.geometry}
            material={nodes.Mesh_55.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_58.geometry}
            material={nodes.Mesh_58.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_59.geometry}
            material={nodes.Mesh_59.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_60.geometry}
            material={nodes.Mesh_60.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_61.geometry}
            material={nodes.Mesh_61.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_62.geometry}
            material={nodes.Mesh_62.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_63.geometry}
            material={nodes.Mesh_63.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_64.geometry}
            material={nodes.Mesh_64.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_65.geometry}
            material={nodes.Mesh_65.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_66.geometry}
            material={nodes.Mesh_66.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_69.geometry}
            material={nodes.Mesh_69.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_70.geometry}
            material={nodes.Mesh_70.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_71.geometry}
            material={nodes.Mesh_71.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_72.geometry}
            material={nodes.Mesh_72.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_75.geometry}
            material={nodes.Mesh_75.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_76.geometry}
            material={nodes.Mesh_76.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_77.geometry}
            material={nodes.Mesh_77.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_78.geometry}
            material={nodes.Mesh_78.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_79.geometry}
            material={nodes.Mesh_79.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_80.geometry}
            material={nodes.Mesh_80.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_81.geometry}
            material={nodes.Mesh_81.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_82.geometry}
            material={nodes.Mesh_82.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_83.geometry}
            material={nodes.Mesh_83.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_84.geometry}
            material={nodes.Mesh_84.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_88.geometry}
            material={nodes.Mesh_88.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_89.geometry}
            material={nodes.Mesh_89.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_90.geometry}
            material={nodes.Mesh_90.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_91.geometry}
            material={nodes.Mesh_91.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_92.geometry}
            material={nodes.Mesh_92.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_93.geometry}
            material={nodes.Mesh_93.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_94.geometry}
            material={nodes.Mesh_94.material}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/assets/gundam_unicorn.gltf')